apiVersion: v1
kind: Service
metadata:
  name: chatapp-service
  namespace: chatapp
  labels:
    app: chatapp
spec:
  selector:
    app: chatapp
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
