apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chatapp-pvc
  namespace: chatapp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi   # Request 500Mi
  storageClassName: gp3  # Use AWS gp3 StorageClass
