apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chatapp-pvc
  namespace: chatapp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: manual
